POST http://localhost:4002/auth/register
content-type: application/json

###

POST http://localhost:4002/product
content-type: application/json

{
    "name": "chimarrão domingo",
    "price": 0.0,
    "approved": true
}

###

GET http://localhost:4002/product

###

GET http://localhost:4002/product/6307a9caec2d89fef86618e6

###

PATCH http://localhost:4002/product/6314e0201a8b6c3e22f62d90
content-type: application/json

{
    "name": "Teclado",
    "price": 119.9,
    "approved": true
}

###

PUT http://localhost:4002/product/df0c5b8b-39d5-4b87-96f7-49eda8893760
content-type: application/json

{
    "name": "caderno 96 folhas preto",
    "price": 10.55,
    "approved": true
}

###

DELETE http://localhost:4002/product/6314aa52276fc0539184f96a