POST http://localhost:4002/product
content-type: application/json

{
    "name": "Caneca Dev",
    "price": 49.90,
    "approved": true
}

###

GET http://localhost:4002/product

###

GET http://localhost:4002/product/6314aa9c276fc0539184f96c

###

PATCH http://localhost:4002/product/63079525e9a7cd26872e3bf9
content-type: application/json

{
    "name": "Testando atualização",
    "price": 2.99,
    "approved": true
}

###

PUT http://localhost:4002/product/df0c5b8b-39d5-4b87-96f7-49eda8893760
content-type: application/json

{
    "name": "caderno 96 folhas preto",
    "price": 10.55,
    "approved": true
}

###

DELETE http://localhost:4002/product/63079525e9a7cd26872e3bf9